"""Diffusion Attack Detector.

Specifically detects diffusion-generated audio using:
- Noise residual analysis
- Frequency-domain fingerprints
- Multi-resolution spectrogram artifacts
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

from ads.config.settings import settings

logger = logging.getLogger(__name__)


class ResidualBlock(nn.Module):
    """Residual block for audio feature processing."""

    def __init__(self, channels: int) -> None:
        super().__init__()
        self.conv1 = nn.Conv1d(channels, channels, 3, padding=1)
        self.bn1 = nn.BatchNorm1d(channels)
        self.conv2 = nn.Conv1d(channels, channels, 3, padding=1)
        self.bn2 = nn.BatchNorm1d(channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = x
        x = F.gelu(self.bn1(self.conv1(x)))
        x = self.bn2(self.conv2(x))
        return F.gelu(x + residual)


class DiffusionDetectorBranch(nn.Module):
    """Diffusion attack detector.

    Detects audio generated by diffusion models (e.g., AudioLDM, DiffWave).
    Uses noise residual analysis and frequency-domain fingerprints
    characteristic of diffusion-based generation.

    Architecture:
    - Multi-scale spectral analysis
    - Noise residual estimation
    - Frequency fingerprint extraction
    - Classification head
    """

    def __init__(self, config: Optional[dict] = None) -> None:
        super().__init__()
        self.config = config or {}
        self.model_dim = self.config.get("model_dim", settings.diffusion_detector.model_dim)
        self.num_res_blocks = self.config.get("num_res_blocks", settings.diffusion_detector.num_res_blocks)
        self.use_noise_residual = self.config.get("use_noise_residual", settings.diffusion_detector.use_noise_residual)
        self.use_freq_fingerprint = self.config.get("use_freq_fingerprint", settings.diffusion_detector.use_freq_fingerprint)
        self.embedding_dim = self.config.get("embedding_dim", settings.diffusion_detector.embedding_dim)

        self.stft = nn.Sequential(
            nn.Conv1d(1, 32, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm1d(32),
            nn.GELU(),
        )

        self.res_blocks = nn.ModuleList([
            ResidualBlock(32) for _ in range(self.num_res_blocks)
        ])

        self.freq_encoder = nn.Sequential(
            nn.Conv1d(32, 64, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm1d(64),
            nn.GELU(),
            nn.AdaptiveAvgPool1d(1),
        )

        if self.use_noise_residual:
            self.noise_estimator = nn.Sequential(
                nn.Conv1d(1, 16, kernel_size=5, padding=2),
                nn.BatchNorm1d(16),
                nn.GELU(),
                nn.Conv1d(16, 1, kernel_size=5, padding=2),
            )

        self.freq_fingerprint_net = nn.Sequential(
            nn.Linear(512, 128),
            nn.LayerNorm(128),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(128, self.embedding_dim),
        )

        self.embedding_proj = nn.Sequential(
            nn.Linear(64 + self.embedding_dim, self.embedding_dim),
            nn.LayerNorm(self.embedding_dim),
            nn.GELU(),
        )

        self.classifier = nn.Sequential(
            nn.Linear(self.embedding_dim, 64),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(64, 1),
        )

    def forward(
        self,
        waveform: torch.Tensor,
        spectral_features: Optional[torch.Tensor] = None,
        return_embedding: bool = False,
    ) -> Dict[str, torch.Tensor]:
        """Detect diffusion-generated audio.

        Args:
            waveform: Audio waveform (batch, samples) or (samples,)
            spectral_features: Optional pre-computed spectral features
            return_embedding: Whether to return embeddings

        Returns:
            Dict with logits, embedding, diffusion_probability
        """
        if waveform.dim() == 1:
            waveform = waveform.unsqueeze(0).unsqueeze(1)
        elif waveform.dim() == 2:
            waveform = waveform.unsqueeze(1)

        x = self.stft(waveform)

        for block in self.res_blocks:
            x = block(x)

        time_features = self.freq_encoder(x).squeeze(-1)

        freq_embedding = torch.zeros(waveform.shape[0], self.embedding_dim, device=waveform.device)
        if self.use_freq_fingerprint:
            freq_spec = torch.stft(
                waveform.squeeze(1),
                n_fft=1024,
                hop_length=256,
                win_length=1024,
                return_complex=True,
            ).abs()
            freq_flat = freq_spec.view(waveform.shape[0], -1)[:, :512]
            freq_embedding = self.freq_fingerprint_net(freq_flat)

        combined = torch.cat([time_features, freq_embedding], dim=-1)
        embedding = self.embedding_proj(combined)
        logits = self.classifier(embedding)

        result = {
            "logits": logits,
            "embedding": embedding if return_embedding else embedding.detach(),
            "confidence": torch.sigmoid(logits),
            "diffusion_probability": torch.sigmoid(logits),
        }

        if self.use_noise_residual:
            noise_residual = self.noise_estimator(waveform)
            result["noise_residual"] = noise_residual

        return result
