"""
DeepGuard Platform — Video Detection Subsystem (VDS)
Module  : engines.video-engine.explainability.report_generator
Layer   : Layer 5 — Explainability

Generates comprehensive Markdown and JSON forensic reports.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict


class ForensicReportGenerator:
    """Compiles fusion and localization results into analyst reports."""

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        fusion_result: Any,
        localization_result: Any,
        graph_paths: Dict[str, Path],
    ) -> Path:
        """
        Generates the forensic_summary.md report.
        """
        report_path = self.output_dir / "forensic_summary.md"
        json_path = self.output_dir / "forensic_summary.json"

        # Safe extraction
        overall_verdict = getattr(fusion_result, "overall_verdict", "UNCERTAIN")
        overall_confidence = getattr(fusion_result, "overall_confidence", 0.0)
        track_results = getattr(fusion_result, "track_results", {})

        fps = 8.0
        duration_s = 0.0
        n_frames = 0
        manipulated_frames = getattr(localization_result, "manipulated_frames", [])
        audio_timestamps = getattr(localization_result, "audio_timestamps", [])

        if localization_result:
            meta = getattr(localization_result, "metadata", {})
            fps = meta.get("fps", 8.0)
            duration_s = meta.get("duration_s", 0.0)
            n_frames = meta.get("n_frames_analyzed", 0)

        # Build Markdown content
        md = [
            "# DeepGuard VDS — Forensic Summary Report",
            "",
            f"**Overall Verdict:** `{overall_verdict}`",
            f"**Confidence:** {overall_confidence:.2%}",
            f"**Video Duration:** {duration_s:.2f} seconds ({n_frames} frames analyzed at {fps:.1f} FPS)",
            "",
            "## 1. Localization Summary",
        ]

        if manipulated_frames:
            seconds_list = [f / fps for f in manipulated_frames]
            min_sec = min(seconds_list)
            max_sec = max(seconds_list)
            md.append(f"- **Visual Manipulations Detected:** Yes (between {min_sec:.1f}s and {max_sec:.1f}s)")
            md.append(f"- **Suspicious Frames Count:** {len(manipulated_frames)}")
        else:
            md.append("- **Visual Manipulations Detected:** None")

        if audio_timestamps:
            md.append("- **Audio/Sync Anomalies Detected:** Yes")
            for (start, end) in audio_timestamps:
                md.append(f"  - Interval: {start:.1f}s to {end:.1f}s")
        else:
            md.append("- **Audio/Sync Anomalies Detected:** None")

        md.append("")
        md.append("## 2. Track Breakdown & Modality Attribution")

        for track_id, track_res in track_results.items():
            verdict = getattr(track_res, "verdict", "UNCERTAIN")
            conf = getattr(track_res, "confidence", 0.0)
            culprits = getattr(track_res, "modality_culprits", {})

            md.append(f"### Track: {track_id} ({verdict} — {conf:.2%})")
            if culprits:
                md.append("**Primary Artifact Culprits:**")
                for k, v in culprits.items():
                    md.append(f"- **{k.capitalize()}**: {v:.2%}")
            else:
                md.append("No specific culprit data available.")
            md.append("")

        md.append("## 3. Explanatory Visualizations")

        if "temporal" in graph_paths:
            md.append("### Temporal Inconsistency Timeline")
            md.append(f"![Temporal Graph]({graph_paths['temporal'].name})")
            md.append("")

        if "lip_sync" in graph_paths:
            md.append("### Cross-Modal Synchronization")
            md.append(f"![Lip Sync Graph]({graph_paths['lip_sync'].name})")
            md.append("")

        if "rppg" in graph_paths:
            md.append("### Biological Signal (rPPG BVP)")
            md.append(f"![rPPG Graph]({graph_paths['rppg'].name})")
            md.append("")

        if "heatmaps" in graph_paths:
            md.append("### Artifact Frame Heatmaps")
            md.append(f"Refer to the output directory for `heatmap_frame_*.png` overlays.")
            md.append("")

        md.append("---")
        md.append("*Generated by DeepGuard Video Detection Subsystem (Layer 5)*")

        # Write Markdown
        with open(report_path, "w", encoding="utf-8") as f:
            f.write("\n".join(md))

        # Write JSON payload
        json_payload = {
            "overall_verdict": overall_verdict,
            "overall_confidence": overall_confidence,
            "duration_s": duration_s,
            "fps": fps,
            "manipulated_frames": manipulated_frames,
            "audio_timestamps": audio_timestamps,
            "tracks": {
                tid: {
                    "verdict": getattr(tres, "verdict", "UNCERTAIN"),
                    "confidence": getattr(tres, "confidence", 0.0),
                    "culprits": getattr(tres, "modality_culprits", {}),
                } for tid, tres in track_results.items()
            }
        }
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(json_payload, f, indent=2)

        return report_path
